# Generated by Django 5.1.2 on 2024-10-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='prodcut',
            new_name='product',
        ),
    ]
